import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Avatar, Header, Pill, Rating, Screen } from '@/components/ChaloUI';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

export default function DriverScreen() {
  const colors = useColors();
  const { selectedRide: ride } = useApp();
  const driver = ride.driver;
  return <Screen><Header title="Driver profile" subtitle="Get to know your host" back onBack={() => router.back()} /><View style={[styles.profile, { backgroundColor: colors.inverseSurface }]}><Avatar initials={driver.initials} size={78} accent /><Text style={[styles.name, { color: colors.inverseForeground }]}>{driver.name}</Text><View style={styles.ratingLine}><Rating value={driver.rating} /><Text style={[styles.light, { color: colors.inverseMuted }]}>Highly rated host</Text></View><View style={styles.verified}><Ionicons name="shield-checkmark" size={15} color={colors.green} /><Text style={[styles.verifiedText, { color: colors.green }]}>Identity verified</Text></View></View><View style={styles.stats}>{[['Trips', `${driver.trips}`], ['Driving', `${driver.years} yrs`], ['Response', driver.responseRate], ['Cancels', driver.cancellationRate]].map(([label, value], index, list) => <View key={label} style={[styles.stat, { borderColor: colors.border, borderRightWidth: index === list.length - 1 ? 0 : 1 }]}><Text style={[styles.statValue, { color: colors.charcoal }]}>{value}</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>{label}</Text></View>)}</View><Text style={[styles.section, { color: colors.charcoal }]}>About {driver.name.split(' ')[0]}</Text><Text style={[styles.bio, { color: colors.mutedForeground }]}>{driver.bio}</Text><Text style={[styles.section, { color: colors.charcoal }]}>Passenger reviews</Text>{driver.reviews.map((review) => <View key={review} style={[styles.review, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.reviewTop}><Rating value={5} /><Pill label="Recent" tone="green" /></View><Text style={[styles.reviewText, { color: colors.charcoal }]}>{review}</Text><Text style={[styles.light, { color: colors.mutedForeground }]}>Passenger · verified trip</Text></View>)}</Screen>;
}
const styles = StyleSheet.create({ profile: { borderRadius: 23, alignItems: 'center', paddingVertical: 24, marginBottom: 15 }, name: { fontFamily: 'Inter_700Bold', fontSize: 22, marginTop: 13 }, ratingLine: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 7 }, light: { fontFamily: 'Inter_400Regular', fontSize: 11 }, verified: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 12 }, verifiedText: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, stats: { flexDirection: 'row', marginBottom: 26 }, stat: { flex: 1, borderRightWidth: 1, alignItems: 'center' }, statValue: { fontFamily: 'Inter_700Bold', fontSize: 15 }, statLabel: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4 }, section: { fontFamily: 'Inter_700Bold', fontSize: 16, marginBottom: 9 }, bio: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20, marginBottom: 24 }, review: { borderWidth: 1, borderRadius: 17, padding: 14, marginBottom: 10 }, reviewTop: { flexDirection: 'row', justifyContent: 'space-between' }, reviewText: { fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 18, marginTop: 12 }, reviewText2: { fontFamily: 'Inter_400Regular', fontSize: 11 } });